SELECT A.PRODUCT_ID, A.PRODUCT_NAME, B.AMOUNT * A.PRICE
FROM FOOD_PRODUCT A JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS "AMOUNT"
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;